# Generated by Django 5.2.1 on 2025-05-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_slug'),
    ]

    operations = [
    ]
